//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASecretCouncil.Host.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ASecretCouncil.Host.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Button_Next {
            get {
                return ResourceManager.GetString("Button_Next", resourceCulture);
            }
        }
        
        internal static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        internal static string Button_Previous {
            get {
                return ResourceManager.GetString("Button_Previous", resourceCulture);
            }
        }
        
        internal static string Form_RoutingMessage {
            get {
                return ResourceManager.GetString("Form_RoutingMessage", resourceCulture);
            }
        }
        
        internal static string Validation_RequiredMessage {
            get {
                return ResourceManager.GetString("Validation_RequiredMessage", resourceCulture);
            }
        }
        
        internal static string Validation_InvalidPhoneLengthMessage {
            get {
                return ResourceManager.GetString("Validation_InvalidPhoneLengthMessage", resourceCulture);
            }
        }
        
        internal static string Validation_InvalidPdfMessage {
            get {
                return ResourceManager.GetString("Validation_InvalidPdfMessage", resourceCulture);
            }
        }
        
        internal static string Validation_EmptyPdfMessage {
            get {
                return ResourceManager.GetString("Validation_EmptyPdfMessage", resourceCulture);
            }
        }
        
        internal static string Validation_TooLargePdfMessage {
            get {
                return ResourceManager.GetString("Validation_TooLargePdfMessage", resourceCulture);
            }
        }
        
        internal static string Validation_InvalidEmailMessage {
            get {
                return ResourceManager.GetString("Validation_InvalidEmailMessage", resourceCulture);
            }
        }
        
        internal static string Error_InternalErrorMessage {
            get {
                return ResourceManager.GetString("Error_InternalErrorMessage", resourceCulture);
            }
        }
    }
}
